name: Reusable deployment workflow
# call workflows
on: 
  workflow_call:
    inputs:
      ENVIRONMENT: 
        description: "deployment env prod stage"
        required: true
        type: string
      IMAGE_NAME:
        description: "DOCKER IMAGE WITHOUT TAG"
        required: true
        type: string
    secrets:
      KUBECONFIG:
        description: "kubeconfig"
        required: true

jobs:  
  depoy-with-kubectl:
    name: deployment job
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
    runs-on: github-actions-scaleset-config-demo
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7.0.0

      - name: Install kubectl
        run: | 
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

     
              
      
# yq - update item in yaml file - tool yaml querry
      - name: install yq
        run: |
            sudo curl -L "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -o /usr/local/bin/yq 
            sudo chmod +x /usr/local/bin/yq
            yq --version

      - name: update image name in deployment yaml file
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA:0:7}"
          export IMAGE="${{ inputs.IMAGE_NAME }}:${IMAGE_TAGS}"
          yq e '.spec.template.spec.containers[0].image = strenv(IMAGE)' manifests/deployment.yaml -i
          cat manifests/deployment.yaml

      - name: create namespace if not exist
        run: | 
         kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE

      - name: update image name in deployment yaml file  
        run: |    
          kubectl apply -f manifest/ -n $NAMESPACE
          kubectl get all -n $NAMESPACE

